export const IL18N = {
  en: {
    search: 'Search',
    filters: 'Filters',
    weight: 'Weight',
    height: 'Height',
    base: 'Base',
    stats: 'Stats',
    attack: 'Attack',
    defense: 'Defense',
    sp_attack: 'Sp. Attack',
    sp_defense: 'Sp. Defense',
    speed: 'Speed',
    filter_by_id: 'Filter by id range',
    min: 'Min:',
    max: 'Max:',
    filter_by_type: 'Filter by type',
    reset_filters: 'Reset filters',
    filter: 'Filter',
    all: 'All',
    no_results: 'No results found',
  },
  es: {
    search: 'Buscar',
    filters: 'Filtros',
    weight: 'Peso',
    height: 'Altura',
    base: 'Base',
    stats: 'Estadísticas',
    attack: 'Ataque',
    defense: 'Defensa',
    sp_attack: 'Ataque esp.',
    sp_defense: 'Defensa esp.',
    speed: 'Velocidad',
    filter_by_id: 'Filtrar por rango de id',
    min: 'Mín:',
    max: 'Máx:',
    filter_by_type: 'Filtrar por tipo',
    reset_filters: 'Reiniciar filtros',
    filter: 'Filtrar',
    all: 'Todos',
    no_results: 'No se encontraron resultados',
  },
  fr: {
    search: 'Rechercher',
    filters: 'Filtres',
    weight: 'Poids',
    height: 'Taille',
    base: 'Base',
    stats: 'Statistiques',
    attack: 'Attaque',
    defense: 'Défense',
    sp_attack: 'Attaque spé.',
    sp_defense: 'Défense spé.',
    speed: 'Vitesse',
    filter_by_id: "Filtrer par plage d'id",
    min: 'Min:',
    max: 'Max:',
    filter_by_type: 'Filtrer par type',
    reset_filters: 'Réinitialiser les filtres',
    filter: 'Filtrer',
    all: 'Tous',
    no_results: 'Aucun résultat trouvé',
  },
  pt: {
    search: 'Procurar',
    filters: 'Filtros',
    weight: 'Peso',
    height: 'Altura',
    base: 'Base',
    stats: 'Estatísticas',
    attack: 'Ataque',
    defense: 'Defesa',
    sp_attack: 'Ataque esp.',
    sp_defense: 'Defesa esp.',
    speed: 'Velocidade',
    filter_by_id: 'Filtrar por faixa de id',
    min: 'Min:',
    max: 'Máx:',
    filter_by_type: 'Filtrar por tipo',
    reset_filters: 'Redefinir filtros',
    filter: 'Filtrar',
    all: 'Todos',
    no_results: 'Nenhum resultado encontrado',
  },
}

export const API_FCC_PREFIX =
  'https://pokeapi-proxy.freecodecamp.rocks/api/pokemon/'

export const API_ALL_POKEMON =
  'https://pokeapi.co/api/v2/pokemon/?limit=10279&offset=0'

export const API_POKEMON_FILTERED_BY_TYPE_PREFIX = 'https://pokeapi.co/api/v2/type/'

export const API_POKEMON_FILTERED_BY_ID_PREFIX = 'https://pokeapi.co/api/v2/pokemon/'

export const FILTERS_INITIAL_STATE = {
  minId: 1,
  maxId: 10279,
  type: 'all',
}
